TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += devNLL484Laser.db
DB += devNLL484Laser.proto

#=======================================
include $(TOP)/configure/RULES
